# Site settings
title: 'Demo for jekyll-remote-theme with theme jekyll-uno'
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll - used via jekyll-remote-theme'
url: ''
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

remote_theme: matthiaslischka/jekyll-uno

author:
  name: 'tbd'
  #email: 
  #twitter_username: 
  #facebook_username: 
  github_username: crt2019
  #linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
exclude: ['README.md', 'Gemfile']
